### ISSUE TITLE
Running  pub run angular_test on windows gives unhandled exception

### ISSUE THREAD

**Issue by ktsopanakis** [dart-lang/angular_test#45]
For the current project, but also for any other project that includes angular_test in the packages. When running "pub run angular_test" the result is:
```
Unhandled exception:
ProcessException: The system cannot find the file specified.

  Command: pub serve test
#0      main.<main_async_body> (http://localhost:4769/angular_test.dart:28:27)
#1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
#2      _RootZone.runBinary (dart:async/zone.dart:1410)
#3      _FutureListener.handleError (dart:async/future_impl.dart:146)
#4      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
#5      _Future._propagateToListeners (dart:async/future_impl.dart:671)
#6      _Future._completeError (dart:async/future_impl.dart:485)
#7      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
#8      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#10     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
#11     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by ktsopanakis** [comment]
The reason lies in calling Process.start as:
```
final pubServeProcess = await Process.start('pub', const ['serve', 'test']);
```
while in windows, the installation of dart language, creates a "pub.bat" file that is executed instead of a "pub" executable.

**Comment by ktsopanakis** [comment]
Same issue appears in line 82 in file /bin/angular_test.dart:
```
final process = await Process.start('pub', args);
```
which should change to:
```
final process = await Process.start(_pubBin, args);
```

**Comment by daniel-v** [comment]
I ran into this issue unrelated to this package (internal test runner). My workaround to that problem was running pub's snapshot instead of `pub.bat` . 

Running `pub.bat` and then killing it left at least 1 child zombie process which kept blocking a port. Circumventing it by running snapshot seemed to resolve this issue for me.
