### ISSUE TITLE
Router `AppComponent` tests result in EXCEPTION: Bootstrap at least one component before injecting Router

### ISSUE THREAD

**Issue by chalin** [dart-lang/angular_test#61]
Filing this in following to an exchange started via email.

To reproduce:
- `cd site-webdev/examples/ng/doc/toh-5`
- Drop the `@Skip()` from `test/app_test.dart`
- `pub get`
- `pub run angular_test`

This results in:
```
EXCEPTION: Error in asset:angular_tour_of_heroes/lib/app_component.dart class AppComponent - inline template:2:8
  ORIGINAL EXCEPTION: Bootstrap at least one component before injecting Router.
  ORIGINAL STACKTRACE:
  #0      routerPrimaryComponentFactory (package:angular2/src/router/router_providers_common.dart:32:5)
  #1      ViewAppComponentHost0._ROUTER_PRIMARY_COMPONENT_0_4 (package:angular_tour_of_heroes/app_component.template.dart:256:92)
  #2      ViewAppComponentHost0._RouteRegistry_0_5 (package:angular_tour_of_heroes/app_component.template.dart:261:102)
  #3      ViewAppComponentHost0._Router_0_9 (package:angular_tour_of_heroes/app_component.template.dart:281:84)
  #4      ViewAppComponentHost0.injectorGetInternal (package:angular_tour_of_heroes/app_component.template.dart:302:75)
  #5      AppView.injectorGet (package:angular2/src/core/linker/app_view.dart:222:23)
  #6      DebugAppView.injectorGet (package:angular2/src/debug/debug_app_view.dart:97:31)
  #7      ViewAppComponent0.build (package:angular_tour_of_heroes/app_component.template.dart:113:57)
  #8      AppView.create (package:angular2/src/core/linker/app_view.dart:171:12)
  #9      DebugAppView.create (package:angular2/src/debug/debug_app_view.dart:72:26)
  #10     ViewAppComponentHost0.build (package:angular_tour_of_heroes/app_component.template.dart:290:17)
```

Maybe what is needed is a `bootstrap()` equivalent?

**Comment by chalin** [comment]
cc @kwalrath

**Comment by matanlurey** [comment]
I think we decided that `angular_test` was not appropriate for the root component.
